type GearType {
  name: String!
}

type Gear {
  name: String!
  type: GearType
}

type Role {
  name: String!
}

type Member {
  id: ID!
  firstname: String
  lastname: String
  fullname: String
  fullnameAka: String
  pseudo: String
  bio: String
  birth_date: String
  avatar: String
  member_from: String
  member_until: String
  roles: [Role]
  gears: [Gear]
  concerts: [Concert]
  records: [Record]
}

type Song {
  id: ID!
  title: String!
  duration: String
  lyrics: String
  authors: [Member]
  composers: [Member]
  records: [Record]
  concerts: [Concert]
  rank: Int
}

type Record {
  id: ID!
  title: String!
  type: String
  artwork: String
  links: [String]
  recorded: String
  released: String
  songs: [Song]
  members: [Member]
}

type Concert {
  id: ID!
  title: String
  venue: String
  date: String
  poster: String
  members: [Member]
  bands: [String]
  songs: [Song]
}

# The "Query" type is special: it lists all of the available queries that
# clients can execute, along with the return type for each. In this
# case, the "books" query returns an array of zero or more Books (defined above).
type Query {
  members: [Member]
  member(id: ID!): Member
  records: [Record]
  record(id: ID!): Record
  concerts: [Concert]
  concert(id: ID!): Concert
  songs: [Song]
  song(id: ID!): Song
}
